language: java
sudo: required
dist: trusty
install: true

services:
- postgresql
- mysql

addons:
  postgresql: "9.4"
  sonarcloud:
    organization: "noraui"
  firefox: latest
  chrome: stable

jdk:
- openjdk8

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
- chmod +x test/run.sh
- chmod +x test/after_success.sh
- psql -c 'create database noraui owner travis;' -U postgres
- psql -U travis -d noraui -a -f config/noraui-db.sql
- mysql -e 'CREATE DATABASE noraui;'
- mysql --user=travis noraui < config/noraui-db.sql > output.tab

script:
- test/run.sh

after_success:
- test/after_success.sh

cache:
  directories:
    - $HOME/.m2/repository

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b8f036338cae1f916682
    on_failure: always  # options: [always|never|change] default: always
